  import { Geist, Geist_Mono } from "next/font/google";
  import { Inter } from "next/font/google";
  // import 'react-toastify/dist/ReactToastify.css';
  import { Slide, ToastContainer } from 'react-toastify';
  import "./globals.css";
  import { AuthProvider } from "@/context/AuthContext";

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
  });  

  export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }) {
    return (
      <html  lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
        >
          <AuthProvider>
            {children}
            <ToastContainer
              position="top-right"
              autoClose={2000}
              hideProgressBar={true}
              newestOnTop={false}
              closeOnClick
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored"
              transition={Slide}
            />
          </AuthProvider>
        </body>
      </html>
    );
  }
